title: Rinad H. Almjishai
description: Data Science student portfolio
# remote_theme: pages-themes/minimal@v0.2.0 # Comment this out to use your custom CSS
baseurl: "" # Leave blank for root deployment
url: "https://RinDataz.github.io/portfolio"
