title: Rinad H. Almjishai
logo: https://media.licdn.com/dms/image/D4E03AQF0MXbsdLtq1A/profile-displayphoto-shrink_400_400/0/1714148566032?e=1726099200&v=beta&t=jrmly5IVezwjXTZr56nMo2v7R-WOssvbDM-BJBzvDhs
description: Data Science student at the University of Jeddah, specializing in Machine Learning and Data Engineering. Passionate about FinTech and leveraging data for insights and innovation.
author: Rinad H. Almjishai
email: RinadH.Almjishai@gmail.com
url: https://RinDataz.github.io/portfolio
baseurl: "" # Leave this empty for root
github_username: RinDataz
linkedin_username: renad-hassan-dataz
nav_links:
  - name: "About Me"
    url: "/about"
  - name: "Projects"
    url: "/projects"
  - name: "Skills"
    url: "/skills"
  - name: "Contact"
    url: "/contact"
social_links:
  github: https://github.com/RinDataz
  linkedin: https://www.linkedin.com/in/renad-hassan-dataz/
  email: RinadH.Almjishai@gmail.com
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
