title: Rinad H.Almjishai 
logo: https://media.licdn.com/dms/image/D4E03AQF0MXbsdLtq1A/profile-displayphoto-shrink_400_400/0/1714148566032?e=1726099200&v=beta&t=jrmly5IVezwjXTZr56nMo2v7R-WOssvbDM-BJBzvDhs
description: Data Science student at the University of Jeddah, currently focusing on Machine Learning and Data Engineering. I am passionate about FinTech and leveraging data to drive insights and innovation.
#show_downloads: true
#theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
