<h1>Rinad Hassan Almjishai</h1>
<p>Data Scientist based in Jeddah, Saudi Arabia.</p>
<p>Email: RinadH.Almjishai@gmail.com</p>
<p><a href="https://www.linkedin.com/in/renad-hassan-dataz/">LinkedIn</a></p>

<section id="projects">
  <div class="project">
    <h2>Credit Card Fraud Detection Model</h2>
    <p>Developed a machine learning model using Python and scikit-learn to detect fraudulent credit card transactions, achieving 98% accuracy.</p>
  </div>
  <div class="project">
    <h2>Cyclitic Bike-Share Data Analysis</h2>
    <p>Analyzed Cyclitic bike-share data using Python and SQL, creating reports and dashboards that enhanced operational efficiency.</p>
  </div>
</section>

<ul id="skills">
  <li>PyTorch, Scikit-learn, NumPy, Pandas</li>
  <li>MySQL, SQL Server, PostgreSQL</li>
  <li>HTML, CSS, Flask</li>
</ul>
